### ISSUE TITLE
Unexpected `expire_height` in `Name.properties.info.properties.claims`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1348]
```yaml
    Name:
      description: Name
      properties:
        active:
          example: true
          type: boolean
        hash:
          example: nm_2YmgvoUhVua9wEYGpMj9ybctbQXHPbY9Ppu4CoKoUm8jjFfcsc
          type: string
        info:
          example: trustwallet.chain
          properties:
            active_from:
              example: 163282
              type: integer
            claims:
              example: 362026
              expire_height: null
              items:
                type: integer
              type: integer
```
isn't `expire_height` meant to be a separate property?

> Schema violation: must NOT have additional properties
      (components > schemas > Name > properties > info > properties > claims)
      additionalProperty: expire_height
