### ISSUE TITLE
`tx_type` of `/txs/count` should be `in: query` parameter

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1349]
```yaml
  /txs/count:
    get:
      deprecated: false
      description: Get count of transactions at the latest height.
      operationId: get_tx_count
      parameters:
      - description: Type of a transaction
        in: path
        name: tx_type
        required: false
        schema:
          type: string
          x-example: contract_call
```
 From readme
> $ curl -s "https://mainnet.aeternity.io/mdw/v2/txs/count?tx_type=oracle_register" | jq '.'
286
