### ISSUE TITLE
Setting `system.dev_mode = true` doesn't set network id to `ae_dev`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1760]
Here is a minimum dev mode configuration of the node

docker-compose.yml
```yaml
services:
  middleware:
    image: aeternity/aeternity:v7.0.0
    ports: [3013:3013]
    volumes:
      - ./docker/aeternity.yaml:/home/aeternity/node/aeternity.yaml
```

docker/aeternity.yaml
```yaml
system:
  dev_mode: true

chain:
  persist: false
  hard_forks:
    "1": 0
    "6": 1
```

Here is that [status](http://localhost:3013/v3/status) endpoint returns
```json
{
  "difficulty": 1338,
  "genesis_key_block_hash": "kh_CciVD7Zb38Dwon8AHWDpNK1LatrprLLWGDLTtkUjZqerpxS1o",
  "hashrate": 0,
  "listening": true,
  "network_id": "ae_dev",
  "node_revision": "a9498268ce1ac837e553bba94d5dc6bdc455be11",
  "node_version": "7.0.0",
  "peer_connections": {
    "inbound": 0,
    "outbound": 0
  },
  "peer_count": 0,
  "peer_pubkey": "pp_2NFQGHYHkVi4Q2BTf4xkzFh6h6JzrstdZwoonPPTpu9ZSiyfRw",
  "pending_transactions_count": 0,
  "protocols": [
    {
      "effective_at_height": 1,
      "version": 6
    },
    {
      "effective_at_height": 0,
      "version": 1
    }
  ],
  "solutions": 0,
  "sync_progress": 100.0,
  "syncing": false,
  "top_block_height": 1,
  "top_key_block_hash": "kh_2GFD3CP4djZKx3uk1s9Vjmagu5jxmb1W3GsW8ydN85iKkX6Upp",
  "uptime": "19s.610"
}
```

Using the same configuration with `ae_mdw` I'm getting different results
```yaml
services:
  middleware:
    image: aeternity/ae_mdw:1.75.0
    ports: [4000:4000, 3013:3013]
    volumes:
      - ./docker/aeternity.yaml:/home/aeternity/aeternity.yaml
```
Firstly, the message "[info] Set app_ctrl mode: dev_mode" appears the same way as in the previous setup, but the network id reported by http://localhost:3013/v3/status is ae_mainnet, and the node starts to sync. I expect it to be in dev mode and have `ae_dev` network id, the same way as in plain node.
