### ISSUE TITLE
Next path returns the same activities, stuck on "fee_lock_name"

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1883]
There is a case when `next`, `prev` paths lead to the same page, making it impossible to navigate to subsequent pages.

### Steps to reproduce

docker compose
```yaml
services:
  middleware:
    image: aeternity/ae_mdw:1.82.2
    ports: [4000:4000, 4001:4001, 3013:3013, 3014:3014, 3313:3313]
    volumes:
      - ./middleware.yaml:/home/aeternity/aeternity.yaml
```
middleware.yaml
```yaml
http:
  endpoints:
    dry-run: true

chain:
  persist: false
  hard_forks:
    "1": 0
    "6": 1
  genesis_accounts:
    ak_21A27UVVt3hDkBE5J7rhhqnH5YNb4Y1dqo4PnSybrH85pnWo7E: 10000000000000000000000

fork_management:
  network_id: ae_local

mining:
  beneficiary: ak_21A27UVVt3hDkBE5J7rhhqnH5YNb4Y1dqo4PnSybrH85pnWo7E
  autostart: true
  expected_mine_rate: 1000
  micro_block_cycle: 300
  strictly_follow_top: true
  cuckoo:
    miner:
      executable: mean15-generic
      extra_args: ""
      edge_bits: 15
```
package.json
```json
{
  "dependencies": {
    "@aeternity/aepp-sdk": "github:aeternity/aepp-sdk-js#3fc8b0a60db8a666b1bf0e338d2ad94297f58e6f"
  }
}
```
init.mjs
```js
import {
  Node, AeSdkMethods, MemoryAccount, CompilerHttp, Name
} from '@aeternity/aepp-sdk';

const aeSdk = new AeSdkMethods({
  onAccount: new MemoryAccount('sk_2CuofqWZHrABCrM7GY95YSQn8PyFvKQadnvFnpwhjUnDCFAWmf'),
  onNode: new Node('http://localhost:3013'),
  onCompiler: new CompilerHttp('http://localhost:3080'),
  _expectedMineRate: 0,
  _microBlockCycle: 0,
});

const presetAccount1 = new MemoryAccount('sk_2bmJRanV8TmJzts8SYvBhR2kAd5pceVLczT5Sr8phybZYk4DRD');
const presetAccount1Address = presetAccount1.address;

async function initData() {
  console.log('waiting for height 30 to have stable block time');
  await aeSdk.awaitHeight(30);
  console.log('spend to', presetAccount1Address);
  await aeSdk.spend(1e18, presetAccount1Address);
  const params1 = { ...aeSdk.getContext(), onAccount: presetAccount1 };
  const name1 = new Name('123456789012345678901234567800.chain', params1);
  console.log('name claim');
  await name1.claim();
}

await initData();
```
Execute:
```bash
docker compose up -d
npm install # ~3 minutes
node init.mjs
```
After that navigate to http://localhost:4000/v3/accounts/ak_2Fh6StA76AKdy8qsGdkEfkQyVmAYc2XE1irWRnDgXKhmBLKoXg/activities?limit=1
```json
{
  "data": [
    {
      "type": "InternalTransferEvent",
      "height": 33,
      "block_hash": "mh_2acHQih59XjWammmseHFEUWY5856RRUMfFRZsKQcKmCQxsiTsP",
      "payload": {
        "kind": "fee_lock_name",
        "amount": 3,
        "ref_tx_hash": "th_2TsrsytU8dBpX462SsxBriPcHYZoAUCTcYXryc3YtynuunW2pM"
      },
      "block_time": 1722925198533
    }
  ],
  "next": "/v3/accounts/ak_2Fh6StA76AKdy8qsGdkEfkQyVmAYc2XE1irWRnDgXKhmBLKoXg/activities?cursor=33-2-0&limit=1",
  "prev": null
}
```
go by `next` path
```json
// http://localhost:4000/v3/accounts/ak_2Fh6StA76AKdy8qsGdkEfkQyVmAYc2XE1irWRnDgXKhmBLKoXg/activities?cursor=33-2-0&limit=1
{
  "data": [
    {
      "type": "InternalTransferEvent",
      "height": 33,
      "block_hash": "mh_2acHQih59XjWammmseHFEUWY5856RRUMfFRZsKQcKmCQxsiTsP",
      "payload": {
        "kind": "fee_lock_name",
        "amount": 3,
        "ref_tx_hash": "th_2TsrsytU8dBpX462SsxBriPcHYZoAUCTcYXryc3YtynuunW2pM"
      },
      "block_time": 1722925198533
    }
  ],
  "next": "/v3/accounts/ak_2Fh6StA76AKdy8qsGdkEfkQyVmAYc2XE1irWRnDgXKhmBLKoXg/activities?cursor=33-2-0&limit=1",
  "prev": "/v3/accounts/ak_2Fh6StA76AKdy8qsGdkEfkQyVmAYc2XE1irWRnDgXKhmBLKoXg/activities?cursor=33-2-1&limit=1&rev=1"
}
```
So, the returned data and the `next` path are the same.

There is the same issue going backward.
