### ISSUE TITLE
Define `source_tx_type` as an enum instead of a string

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#2082]
Currently, in multiple places, it is defined as

```yaml
source_tx_type:
  type: string
  example: NameTransferTx
```
https://github.com/aeternity/ae_mdw/blob/e278d0c0b8723028193b74a9412932e2858f5f61/docs/swagger_v3/names.spec.yaml#L261-L263

would be good to list all possible values. So the developer can handle all possible cases on his side.
